model:
  provider: openai   # openai or google
  name: gpt-4o-2024-11-20
  temperature: 0

interviewee:
  mode: "llm" # "human" or "llm"
  wait_human_sec: null  # 人間が回答するまでの待機時間

run:
  wait_time: 3
  out_dir: "out/NLP/llm_interviewee/IT_engineer"

interview:
  max_total_count: 50  #デフォルト値：50
  min_total_count: 48  #デフォルト値：48
  use_question_slot_in_fill_slots: true  #true or false
  slot_selection_mode: "random"  #"random" or "llm"
  estimate_persona: "キャリア・職場: 未  \n思い出・エピソード: 未  \n個人の基本的情報: 未" #デフォルト値 null
  persona_attribute_candidates: # スロット属性候補(デフォルトは50個)
    - 趣味
    - 家族
    - 100年後の未来
    - 好きな芸能人
    - 金銭感覚の違い
  slots:
    資産運用の考え方: null
    パソコンを使う頻度: null
    スポーツジムの利用: null
    語学学習のポイント: null
    学生時代の得意科目: null
    時間管理で気をつけていること: null
    尊敬する人: null
    通勤時の移動方法: null
    在宅ワーク: null
    個人の基本的情報: null
    職場での役割と責任: null
    技術的スキルセット: null
    飼っているペット: null
    好きな言葉・座右の銘: null
    昨日起きたとても悲しい出来事: null
    断捨離や片付けのコツ: null
    服装の好み: null
    使用しているスマートフォンアプリ: null
    思い出・エピソード: null
    好きなお菓子: null
    副業: null
    好きなゆるキャラ: null
    海外旅行の楽しみ方: null
    昇進・転職: null
    感情のコントロールで気をつけていること: null
    チーム内のコミュニケーション: null
    人生で一番つらかった出来事: null
    作るのが得意な料理: null
    行ってみたい国: null
    オンライン会議における悩みごと: null
    スポーツ観戦: null
    悩みや不満点: null
    株式投資の経験: null
    現在のキャリア: null
    人脈の広げ方: null
    SNS: null
    学生時代の失敗エピソード: null
    過去のキャリア: null
    恋愛: null
    起床後のルーティン: null
    未来像: null
    タスク管理: null
    乗りたい車: null
    好きな音楽: null
    かかりつけの病院: null
    好きな食べ物: null
    性格: null
    嫌いな食べ物: null

paths:
  prompts:
    # fill_slots: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain_tsuchida/prompt_fill_slots.txt"
    fill_slots: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain_tsuchida/prompt_fill_slots_show_question_slot.txt"
    generate_slots: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain_tsuchida/prompt_generate_slots.txt"
    generate_slots_2: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain_tsuchida/prompt_generate_slots_2.txt"
    generate_questions: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain_tsuchida/prompt_generating_question.txt"
    user_simulator: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain/prompt_user_simulator.txt"
    end_conversation: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain_tsuchida/prompt_end_conversation.txt"
    estimate_persona: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain_tsuchida/prompt_estimate_persona-zeroshot.txt"
    fukabori_questions: "/mnt/work/interview/data/hashimoto-nakano/prompt_semi_const/proposed_method/all_domain_tsuchida/prompt_fukabori_questions.txt"
  persona_settings: "/mnt/work/interview/data/hashimoto-nakano/persona_settings/IT_engineer-Persona-Sonoda-202510/03.txt"
